# 13.Numpy Arrays

In [1]:
# import the numpy package as np
import numpy as np

In [2]:
# Create 2 new lists height and weight

height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Create 2 numpy arrays from height and weight

np_height = np.array(height)

np_weight= np.array(weight)

print(np_height)

print(np_weight)

[1.87 1.87 1.82 1.91 1.9  1.85]
[81.65 97.52 95.25 92.98 86.18 88.45]


In [3]:
print(np_height)

[1.87 1.87 1.82 1.91 1.9  1.85]


In [4]:
print(type(np_height))

<class 'numpy.ndarray'>


## Element wise Calculation:

In [5]:
# calculate BMI
bmi=np_weight/np_height**2

#print the result

print(bmi)

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


## Subsetting:

In [6]:
# For a boolean response

print(bmi > 23)

# Print only those observations above 23
bmi[bmi > 23]

[ True  True  True  True  True  True]


array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])

# Exercise:

In [7]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

# Create a numpy array np_weight_kg from weight_kg
np_weightKg=np.array(weight_kg)
    

# Create np_weight_lbs from np_weight_kg
np_weightLBS= np_weightKg*2.2


# Print out np_weight_lbs

print(np_weightLBS)

[179.63  214.544 209.55  204.556 189.596 194.59 ]
